spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  lifetime: 900000

api:
  v1:
    prefix: /api/v1